export const configApp = {
  titleApp: "Mueblería Luxe",
  name: "Mueblería Luxe",
  linKFacebook: "",
  linkInstagram: "",
  linkTwitter: "",
  logo: "logo.png",
  logoSm: "logo-sm.png",
  logoDark: "logo-dark.png",
  email: "muebleria@gmail.com",
  telefono: "0987159087",
  direcicn: "",
  ciudad: "Cuenca-Ecuador",
  version: "",
  environment: process.env.NODE_ENV,
  apiUrl: "https://api.example.com",
  sentryDsn: "",
  analytics: "",
};
