export const data = [
  { id: 1, nombre: "Katherine Giselle	Campoverde Condo" },
  { id: 2, nombre: "Pablo Andrés	Arizaga Guzman" },
  { id: 3, nombre: "Victor Andrés	Calderón Padilla" },
  { id: 4, nombre: "José Bolívar	Hernández Sánchez" },
  { id: 5, nombre: "Johana Marcela	Arqui Cubiña" },
  { id: 6, nombre: "Willan Edison	Portilla Chávez" },
  { id: 7, nombre: "Erick Santiago	Becerra Dumancela" },
  { id: 8, nombre: "Santiago Andrés	Jara Sarmiento" },
  { id: 9, nombre: "Alejandra	Vásquez" },
  { id: 10, nombre: "	Thomas Alesandro	Once Jara" },
  { id: 11, nombre: "	Pablo Sebastian	Ortega Gavilanes" },
  { id: 12, nombre: "	Francisco	Pijuana" },
  { id: 13, nombre: "	Juan Francisco	Jara Villazhañay" },
  { id: 14, nombre: "	Daniel Abraham	Peralta Cabrera" },
  { id: 15, nombre: "	Tania	Bacuilima" },
  { id: 16, nombre: "	Valeria Estefanía	Pintado Dután" },
  { id: 17, nombre: "	Gabriela Johanna	Campoverde Mogrovejo" },
  { id: 18, nombre: "	Romulo Isaac	Cabrera Garcia" },
  { id: 19, nombre: "	María Caridad	Lucero Pesántez" },
  { id: 20, nombre: "	Elias Francisco	Cabrera Garcia" },
  { id: 21, nombre: "	Jennifer Estefanía	Llivisaca Fárez" },
  { id: 22, nombre: "	Pamela	Arévalo" },
  { id: 23, nombre: "	Gabriela Josselyne	Franco Arévalo" },
  { id: 24, nombre: "	Erick Joel	Chiriboga Arévalo" },
  { id: 25, nombre: "	Juan Andrés	Llivisaca Lazo" },
  { id: 26, nombre: "	Nelly Grace	Pauta Revilla" },
  { id: 27, nombre: "	Karla Dayanna	Torres Araujo" },
  { id: 28, nombre: "	Carlos	Suquilanda" },
  { id: 29, nombre: "	David	Quichimbo" },
  { id: 30, nombre: "	Erika	Campoverde" },
  { id: 31, nombre: "	Meri	Pauta" },
  { id: 32, nombre: "	Lesly	Brito" },
  { id: 33, nombre: "	Silvia	Mejia" },
  { id: 34, nombre: "	Tania	Peñaloza" },
  { id: 35, nombre: "	Valentina	Avila" },
  { id: 36, nombre: "	David	Parra" },
  { id: 37, nombre: "	Fernando	Torres" },
  { id: 38, nombre: "	Emanuel	Vásquez" },
  { id: 39, nombre: "	David	Naula" },
  { id: 40, nombre: "	Ivan	Naula" },
  { id: 41, nombre: "	Emily	Lojano" },
  { id: 42, nombre: "	Juan Santiago	Lojano" },
  { id: 43, nombre: "	Esther	Quichimbo" },
  { id: 44, nombre: "	Anthony	Maican" },
  { id: 45, nombre: "	Hugo	Gualato" },
  { id: 46, nombre: "	Carmen	" },
  { id: 47, nombre: "	Liguia	Zenguana" },
  { id: 48, nombre: "	Gustavo	Esposo Silvia" },
  { id: 49, nombre: "Nuevo Nombre Nuevo Apellido" },
];
export const dataGrupos = [
  [24, 2, 11, 23, 41],
  [28, 6, 26, 33, 30],
  [14, 8, 46, 37, 49],
  [31, 32, 34, 4, 13],
  [40, 15, 35, 3, 44],
  [12, 39, 19, 42, 45],
  [21, 25, 1, 5, 48],
  [22, 20, 36, 29, 7],
  [47, 18, 16, 38, 17],
  [43, 27, 10, 9],
];
